### ISSUE TITLE
Unbreakable support

### ISSUE THREAD

**Issue by Titanium0B** [Norbit4/TreeCuter#6]
When breaking with an axe with the NBT **Unbreakable** tag, at first glance, the durability is not spent since it is considered indestructible, but ultimately, at the level of NBT tags, the axe's durability decreases and when it is at 0, the functionality of the plugin for the axe stops working.

**Comment by Norbit4** [comment]
I will fix it. Thanks for the report.

**Comment by Norbit4** [comment]
Fixed
