### ISSUE TITLE
[request] make fatigue effect hidden

### ISSUE THREAD

**Issue by SelynCatto** [Norbit4/TreeCuter#8]
When you give an effect in minecraft using commands, e.g "/effect give @p regeneration 9999 255 true", 9999 is the time of the effect, 255 is the strength, and the boolean is whether or not to have the effect be hidden (not show up in the corner of the screen unless the inventory is open).

Would it be possible to add this to the fatigue effect that slows down the tool usage on trees?

**Comment by Norbit4** [comment]
yes, good idea. I will add this in next update

**Comment by Norbit4** [comment]
Added!
